// The solver contract. Any optimizer (CP-SAT, HiGHS, Gurobi, ...) can sit
// behind it; the Go scheduler validates every answer and falls back to FGD.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: gpudefrag/v1/solver.proto

package gpudefragv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Solver_Place_FullMethodName  = "/gpudefrag.v1.Solver/Place"
	Solver_Defrag_FullMethodName = "/gpudefrag.v1.Solver/Defrag"
	Solver_Health_FullMethodName = "/gpudefrag.v1.Solver/Health"
)

// SolverClient is the client API for Solver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolverClient interface {
	Place(ctx context.Context, in *PlaceRequest, opts ...grpc.CallOption) (*PlaceResponse, error)
	Defrag(ctx context.Context, in *DefragRequest, opts ...grpc.CallOption) (*DefragResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type solverClient struct {
	cc grpc.ClientConnInterface
}

func NewSolverClient(cc grpc.ClientConnInterface) SolverClient {
	return &solverClient{cc}
}

func (c *solverClient) Place(ctx context.Context, in *PlaceRequest, opts ...grpc.CallOption) (*PlaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceResponse)
	err := c.cc.Invoke(ctx, Solver_Place_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solverClient) Defrag(ctx context.Context, in *DefragRequest, opts ...grpc.CallOption) (*DefragResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefragResponse)
	err := c.cc.Invoke(ctx, Solver_Defrag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *solverClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Solver_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolverServer is the server API for Solver service.
// All implementations must embed UnimplementedSolverServer
// for forward compatibility.
type SolverServer interface {
	Place(context.Context, *PlaceRequest) (*PlaceResponse, error)
	Defrag(context.Context, *DefragRequest) (*DefragResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedSolverServer()
}

// UnimplementedSolverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSolverServer struct{}

func (UnimplementedSolverServer) Place(context.Context, *PlaceRequest) (*PlaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Place not implemented")
}
func (UnimplementedSolverServer) Defrag(context.Context, *DefragRequest) (*DefragResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Defrag not implemented")
}
func (UnimplementedSolverServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSolverServer) mustEmbedUnimplementedSolverServer() {}
func (UnimplementedSolverServer) testEmbeddedByValue()                {}

// UnsafeSolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolverServer will
// result in compilation errors.
type UnsafeSolverServer interface {
	mustEmbedUnimplementedSolverServer()
}

func RegisterSolverServer(s grpc.ServiceRegistrar, srv SolverServer) {
	// If the following call panics, it indicates UnimplementedSolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Solver_ServiceDesc, srv)
}

func _Solver_Place_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverServer).Place(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Solver_Place_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverServer).Place(ctx, req.(*PlaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Solver_Defrag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefragRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverServer).Defrag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Solver_Defrag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverServer).Defrag(ctx, req.(*DefragRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Solver_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Solver_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Solver_ServiceDesc is the grpc.ServiceDesc for Solver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Solver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gpudefrag.v1.Solver",
	HandlerType: (*SolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Place",
			Handler:    _Solver_Place_Handler,
		},
		{
			MethodName: "Defrag",
			Handler:    _Solver_Defrag_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Solver_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gpudefrag/v1/solver.proto",
}
