// The solver contract. Any optimizer (CP-SAT, HiGHS, Gurobi, ...) can sit
// behind it; the Go scheduler validates every answer and falls back to FGD.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.5
// source: gpupack/v1/solver.proto

package gpupackv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One class of FGD's typical-pod distribution.
type TypicalClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int64                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`                           // milli-CPU
	GpuMilli      int64                  `protobuf:"varint,2,opt,name=gpu_milli,json=gpuMilli,proto3" json:"gpu_milli,omitempty"` // per-GPU milli; 0 = CPU-only class
	GpuNum        int32                  `protobuf:"varint,3,opt,name=gpu_num,json=gpuNum,proto3" json:"gpu_num,omitempty"`
	Pct           float64                `protobuf:"fixed64,4,opt,name=pct,proto3" json:"pct,omitempty"` // 0..1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypicalClass) Reset() {
	*x = TypicalClass{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypicalClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypicalClass) ProtoMessage() {}

func (x *TypicalClass) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypicalClass.ProtoReflect.Descriptor instead.
func (*TypicalClass) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{0}
}

func (x *TypicalClass) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *TypicalClass) GetGpuMilli() int64 {
	if x != nil {
		return x.GpuMilli
	}
	return 0
}

func (x *TypicalClass) GetGpuNum() int32 {
	if x != nil {
		return x.GpuNum
	}
	return 0
}

func (x *TypicalClass) GetPct() float64 {
	if x != nil {
		return x.Pct
	}
	return 0
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CpuLeft       int64                  `protobuf:"varint,2,opt,name=cpu_left,json=cpuLeft,proto3" json:"cpu_left,omitempty"`
	MemLeft       int64                  `protobuf:"varint,3,opt,name=mem_left,json=memLeft,proto3" json:"mem_left,omitempty"`
	GpuLeft       []int64                `protobuf:"varint,4,rep,packed,name=gpu_left,json=gpuLeft,proto3" json:"gpu_left,omitempty"`             // milli-GPU free per device
	ClassAccess   []bool                 `protobuf:"varint,5,rep,packed,name=class_access,json=classAccess,proto3" json:"class_access,omitempty"` // per TypicalClass: GPU type accessible
	Domain        string                 `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`                                      // topology domain (M4)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{1}
}

func (x *Node) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Node) GetCpuLeft() int64 {
	if x != nil {
		return x.CpuLeft
	}
	return 0
}

func (x *Node) GetMemLeft() int64 {
	if x != nil {
		return x.MemLeft
	}
	return 0
}

func (x *Node) GetGpuLeft() []int64 {
	if x != nil {
		return x.GpuLeft
	}
	return nil
}

func (x *Node) GetClassAccess() []bool {
	if x != nil {
		return x.ClassAccess
	}
	return nil
}

func (x *Node) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type Pod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cpu           int64                  `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem           int64                  `protobuf:"varint,3,opt,name=mem,proto3" json:"mem,omitempty"`
	GpuNum        int32                  `protobuf:"varint,4,opt,name=gpu_num,json=gpuNum,proto3" json:"gpu_num,omitempty"`
	GpuMilli      int64                  `protobuf:"varint,5,opt,name=gpu_milli,json=gpuMilli,proto3" json:"gpu_milli,omitempty"`
	Candidates    []int32                `protobuf:"varint,6,rep,packed,name=candidates,proto3" json:"candidates,omitempty"` // node ids the pod may use
	Weight        int64                  `protobuf:"varint,7,opt,name=weight,proto3" json:"weight,omitempty"`                // value of placing it
	Gang          int32                  `protobuf:"varint,8,opt,name=gang,proto3" json:"gang,omitempty"`                    // 0 = no gang (M4)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{2}
}

func (x *Pod) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pod) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Pod) GetMem() int64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *Pod) GetGpuNum() int32 {
	if x != nil {
		return x.GpuNum
	}
	return 0
}

func (x *Pod) GetGpuMilli() int64 {
	if x != nil {
		return x.GpuMilli
	}
	return 0
}

func (x *Pod) GetCandidates() []int32 {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *Pod) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Pod) GetGang() int32 {
	if x != nil {
		return x.Gang
	}
	return 0
}

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           int32                  `protobuf:"varint,1,opt,name=pod,proto3" json:"pod,omitempty"`
	Node          int32                  `protobuf:"varint,2,opt,name=node,proto3" json:"node,omitempty"`
	Gpus          []int32                `protobuf:"varint,3,rep,packed,name=gpus,proto3" json:"gpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{3}
}

func (x *Assignment) GetPod() int32 {
	if x != nil {
		return x.Pod
	}
	return 0
}

func (x *Assignment) GetNode() int32 {
	if x != nil {
		return x.Node
	}
	return 0
}

func (x *Assignment) GetGpus() []int32 {
	if x != nil {
		return x.Gpus
	}
	return nil
}

// A pattern is one way to fill one node with a subset of the batch, with its
// exact post-placement fragmentation precomputed by the caller (column
// formulation). When patterns are present the solver picks exactly one
// pattern per node instead of building the direct model.
type Pattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          int32                  `protobuf:"varint,1,opt,name=node,proto3" json:"node,omitempty"`
	Assignments   []*Assignment          `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty"` // pods placed on `node` and their GPUs
	Frag          float64                `protobuf:"fixed64,3,opt,name=frag,proto3" json:"frag,omitempty"`             // node fragmentation after placement, milli-GPU
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pattern) Reset() {
	*x = Pattern{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pattern) ProtoMessage() {}

func (x *Pattern) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pattern.ProtoReflect.Descriptor instead.
func (*Pattern) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{4}
}

func (x *Pattern) GetNode() int32 {
	if x != nil {
		return x.Node
	}
	return 0
}

func (x *Pattern) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *Pattern) GetFrag() float64 {
	if x != nil {
		return x.Frag
	}
	return 0
}

type PlaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Pods          []*Pod                 `protobuf:"bytes,2,rep,name=pods,proto3" json:"pods,omitempty"`
	Classes       []*TypicalClass        `protobuf:"bytes,3,rep,name=classes,proto3" json:"classes,omitempty"`
	Hint          []*Assignment          `protobuf:"bytes,4,rep,name=hint,proto3" json:"hint,omitempty"`
	TimeLimitS    float64                `protobuf:"fixed64,5,opt,name=time_limit_s,json=timeLimitS,proto3" json:"time_limit_s,omitempty"`
	Deterministic bool                   `protobuf:"varint,6,opt,name=deterministic,proto3" json:"deterministic,omitempty"`
	Workers       int32                  `protobuf:"varint,7,opt,name=workers,proto3" json:"workers,omitempty"`
	GangDomains   bool                   `protobuf:"varint,8,opt,name=gang_domains,json=gangDomains,proto3" json:"gang_domains,omitempty"` // gangs must stay within one domain (M4)
	Patterns      []*Pattern             `protobuf:"bytes,9,rep,name=patterns,proto3" json:"patterns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceRequest) Reset() {
	*x = PlaceRequest{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceRequest) ProtoMessage() {}

func (x *PlaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceRequest.ProtoReflect.Descriptor instead.
func (*PlaceRequest) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{5}
}

func (x *PlaceRequest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *PlaceRequest) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *PlaceRequest) GetClasses() []*TypicalClass {
	if x != nil {
		return x.Classes
	}
	return nil
}

func (x *PlaceRequest) GetHint() []*Assignment {
	if x != nil {
		return x.Hint
	}
	return nil
}

func (x *PlaceRequest) GetTimeLimitS() float64 {
	if x != nil {
		return x.TimeLimitS
	}
	return 0
}

func (x *PlaceRequest) GetDeterministic() bool {
	if x != nil {
		return x.Deterministic
	}
	return false
}

func (x *PlaceRequest) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *PlaceRequest) GetGangDomains() bool {
	if x != nil {
		return x.GangDomains
	}
	return false
}

func (x *PlaceRequest) GetPatterns() []*Pattern {
	if x != nil {
		return x.Patterns
	}
	return nil
}

type PlaceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Assignments       []*Assignment          `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Status            string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // OPTIMAL, FEASIBLE, ...
	WallS             float64                `protobuf:"fixed64,3,opt,name=wall_s,json=wallS,proto3" json:"wall_s,omitempty"`
	DeterministicTime float64                `protobuf:"fixed64,4,opt,name=deterministic_time,json=deterministicTime,proto3" json:"deterministic_time,omitempty"`
	Frag              float64                `protobuf:"fixed64,5,opt,name=frag,proto3" json:"frag,omitempty"` // solver's objective, milli-GPU
	PlacedWeight      int64                  `protobuf:"varint,6,opt,name=placed_weight,json=placedWeight,proto3" json:"placed_weight,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlaceResponse) Reset() {
	*x = PlaceResponse{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceResponse) ProtoMessage() {}

func (x *PlaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceResponse.ProtoReflect.Descriptor instead.
func (*PlaceResponse) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{6}
}

func (x *PlaceResponse) GetAssignments() []*Assignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *PlaceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlaceResponse) GetWallS() float64 {
	if x != nil {
		return x.WallS
	}
	return 0
}

func (x *PlaceResponse) GetDeterministicTime() float64 {
	if x != nil {
		return x.DeterministicTime
	}
	return 0
}

func (x *PlaceResponse) GetFrag() float64 {
	if x != nil {
		return x.Frag
	}
	return 0
}

func (x *PlaceResponse) GetPlacedWeight() int64 {
	if x != nil {
		return x.PlacedWeight
	}
	return 0
}

// A running pod that the defragmenter may move (M3).
type Movable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Node          int32                  `protobuf:"varint,2,opt,name=node,proto3" json:"node,omitempty"`
	Gpus          []int32                `protobuf:"varint,3,rep,packed,name=gpus,proto3" json:"gpus,omitempty"`
	Cpu           int64                  `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem           int64                  `protobuf:"varint,5,opt,name=mem,proto3" json:"mem,omitempty"`
	GpuNum        int32                  `protobuf:"varint,6,opt,name=gpu_num,json=gpuNum,proto3" json:"gpu_num,omitempty"`
	GpuMilli      int64                  `protobuf:"varint,7,opt,name=gpu_milli,json=gpuMilli,proto3" json:"gpu_milli,omitempty"`
	Cost          int64                  `protobuf:"varint,8,opt,name=cost,proto3" json:"cost,omitempty"`          // migration cost (lost GPU-milli-seconds + restart)
	Dests         []int32                `protobuf:"varint,9,rep,packed,name=dests,proto3" json:"dests,omitempty"` // allowed destination nodes (GPU type, etc.); empty = any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movable) Reset() {
	*x = Movable{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movable) ProtoMessage() {}

func (x *Movable) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movable.ProtoReflect.Descriptor instead.
func (*Movable) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{7}
}

func (x *Movable) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Movable) GetNode() int32 {
	if x != nil {
		return x.Node
	}
	return 0
}

func (x *Movable) GetGpus() []int32 {
	if x != nil {
		return x.Gpus
	}
	return nil
}

func (x *Movable) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Movable) GetMem() int64 {
	if x != nil {
		return x.Mem
	}
	return 0
}

func (x *Movable) GetGpuNum() int32 {
	if x != nil {
		return x.GpuNum
	}
	return 0
}

func (x *Movable) GetGpuMilli() int64 {
	if x != nil {
		return x.GpuMilli
	}
	return 0
}

func (x *Movable) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Movable) GetDests() []int32 {
	if x != nil {
		return x.Dests
	}
	return nil
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           int32                  `protobuf:"varint,1,opt,name=pod,proto3" json:"pod,omitempty"`
	ToNode        int32                  `protobuf:"varint,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	Gpus          []int32                `protobuf:"varint,3,rep,packed,name=gpus,proto3" json:"gpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{8}
}

func (x *Move) GetPod() int32 {
	if x != nil {
		return x.Pod
	}
	return 0
}

func (x *Move) GetToNode() int32 {
	if x != nil {
		return x.ToNode
	}
	return 0
}

func (x *Move) GetGpus() []int32 {
	if x != nil {
		return x.Gpus
	}
	return nil
}

type DefragRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Blocked       []*Pod                 `protobuf:"bytes,2,rep,name=blocked,proto3" json:"blocked,omitempty"`
	Movable       []*Movable             `protobuf:"bytes,3,rep,name=movable,proto3" json:"movable,omitempty"`
	MaxMoves      int32                  `protobuf:"varint,4,opt,name=max_moves,json=maxMoves,proto3" json:"max_moves,omitempty"`
	TimeLimitS    float64                `protobuf:"fixed64,5,opt,name=time_limit_s,json=timeLimitS,proto3" json:"time_limit_s,omitempty"`
	Deterministic bool                   `protobuf:"varint,6,opt,name=deterministic,proto3" json:"deterministic,omitempty"`
	Workers       int32                  `protobuf:"varint,7,opt,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefragRequest) Reset() {
	*x = DefragRequest{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefragRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefragRequest) ProtoMessage() {}

func (x *DefragRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefragRequest.ProtoReflect.Descriptor instead.
func (*DefragRequest) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{9}
}

func (x *DefragRequest) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *DefragRequest) GetBlocked() []*Pod {
	if x != nil {
		return x.Blocked
	}
	return nil
}

func (x *DefragRequest) GetMovable() []*Movable {
	if x != nil {
		return x.Movable
	}
	return nil
}

func (x *DefragRequest) GetMaxMoves() int32 {
	if x != nil {
		return x.MaxMoves
	}
	return 0
}

func (x *DefragRequest) GetTimeLimitS() float64 {
	if x != nil {
		return x.TimeLimitS
	}
	return 0
}

func (x *DefragRequest) GetDeterministic() bool {
	if x != nil {
		return x.Deterministic
	}
	return false
}

func (x *DefragRequest) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

type DefragResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*Move                `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	Placements    []*Assignment          `protobuf:"bytes,2,rep,name=placements,proto3" json:"placements,omitempty"` // blocked pods placed after the moves
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	WallS         float64                `protobuf:"fixed64,4,opt,name=wall_s,json=wallS,proto3" json:"wall_s,omitempty"`
	Benefit       int64                  `protobuf:"varint,5,opt,name=benefit,proto3" json:"benefit,omitempty"`
	Cost          int64                  `protobuf:"varint,6,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefragResponse) Reset() {
	*x = DefragResponse{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefragResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefragResponse) ProtoMessage() {}

func (x *DefragResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefragResponse.ProtoReflect.Descriptor instead.
func (*DefragResponse) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{10}
}

func (x *DefragResponse) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *DefragResponse) GetPlacements() []*Assignment {
	if x != nil {
		return x.Placements
	}
	return nil
}

func (x *DefragResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DefragResponse) GetWallS() float64 {
	if x != nil {
		return x.WallS
	}
	return 0
}

func (x *DefragResponse) GetBenefit() int64 {
	if x != nil {
		return x.Benefit
	}
	return 0
}

func (x *DefragResponse) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_gpupack_v1_solver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gpupack_v1_solver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_gpupack_v1_solver_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_gpupack_v1_solver_proto protoreflect.FileDescriptor

const file_gpupack_v1_solver_proto_rawDesc = "" +
	"\n" +
	"\x17gpupack/v1/solver.proto\x12\n" +
	"gpupack.v1\"h\n" +
	"\fTypicalClass\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x03R\x03cpu\x12\x1b\n" +
	"\tgpu_milli\x18\x02 \x01(\x03R\bgpuMilli\x12\x17\n" +
	"\agpu_num\x18\x03 \x01(\x05R\x06gpuNum\x12\x10\n" +
	"\x03pct\x18\x04 \x01(\x01R\x03pct\"\xa2\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bcpu_left\x18\x02 \x01(\x03R\acpuLeft\x12\x19\n" +
	"\bmem_left\x18\x03 \x01(\x03R\amemLeft\x12\x19\n" +
	"\bgpu_left\x18\x04 \x03(\x03R\agpuLeft\x12!\n" +
	"\fclass_access\x18\x05 \x03(\bR\vclassAccess\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\"\xbb\x01\n" +
	"\x03Pod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\x03R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x03 \x01(\x03R\x03mem\x12\x17\n" +
	"\agpu_num\x18\x04 \x01(\x05R\x06gpuNum\x12\x1b\n" +
	"\tgpu_milli\x18\x05 \x01(\x03R\bgpuMilli\x12\x1e\n" +
	"\n" +
	"candidates\x18\x06 \x03(\x05R\n" +
	"candidates\x12\x16\n" +
	"\x06weight\x18\a \x01(\x03R\x06weight\x12\x12\n" +
	"\x04gang\x18\b \x01(\x05R\x04gang\"F\n" +
	"\n" +
	"Assignment\x12\x10\n" +
	"\x03pod\x18\x01 \x01(\x05R\x03pod\x12\x12\n" +
	"\x04node\x18\x02 \x01(\x05R\x04node\x12\x12\n" +
	"\x04gpus\x18\x03 \x03(\x05R\x04gpus\"k\n" +
	"\aPattern\x12\x12\n" +
	"\x04node\x18\x01 \x01(\x05R\x04node\x128\n" +
	"\vassignments\x18\x02 \x03(\v2\x16.gpupack.v1.AssignmentR\vassignments\x12\x12\n" +
	"\x04frag\x18\x03 \x01(\x01R\x04frag\"\xf1\x02\n" +
	"\fPlaceRequest\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.gpupack.v1.NodeR\x05nodes\x12#\n" +
	"\x04pods\x18\x02 \x03(\v2\x0f.gpupack.v1.PodR\x04pods\x122\n" +
	"\aclasses\x18\x03 \x03(\v2\x18.gpupack.v1.TypicalClassR\aclasses\x12*\n" +
	"\x04hint\x18\x04 \x03(\v2\x16.gpupack.v1.AssignmentR\x04hint\x12 \n" +
	"\ftime_limit_s\x18\x05 \x01(\x01R\n" +
	"timeLimitS\x12$\n" +
	"\rdeterministic\x18\x06 \x01(\bR\rdeterministic\x12\x18\n" +
	"\aworkers\x18\a \x01(\x05R\aworkers\x12!\n" +
	"\fgang_domains\x18\b \x01(\bR\vgangDomains\x12/\n" +
	"\bpatterns\x18\t \x03(\v2\x13.gpupack.v1.PatternR\bpatterns\"\xe0\x01\n" +
	"\rPlaceResponse\x128\n" +
	"\vassignments\x18\x01 \x03(\v2\x16.gpupack.v1.AssignmentR\vassignments\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x15\n" +
	"\x06wall_s\x18\x03 \x01(\x01R\x05wallS\x12-\n" +
	"\x12deterministic_time\x18\x04 \x01(\x01R\x11deterministicTime\x12\x12\n" +
	"\x04frag\x18\x05 \x01(\x01R\x04frag\x12#\n" +
	"\rplaced_weight\x18\x06 \x01(\x03R\fplacedWeight\"\xc5\x01\n" +
	"\aMovable\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04node\x18\x02 \x01(\x05R\x04node\x12\x12\n" +
	"\x04gpus\x18\x03 \x03(\x05R\x04gpus\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x03R\x03cpu\x12\x10\n" +
	"\x03mem\x18\x05 \x01(\x03R\x03mem\x12\x17\n" +
	"\agpu_num\x18\x06 \x01(\x05R\x06gpuNum\x12\x1b\n" +
	"\tgpu_milli\x18\a \x01(\x03R\bgpuMilli\x12\x12\n" +
	"\x04cost\x18\b \x01(\x03R\x04cost\x12\x14\n" +
	"\x05dests\x18\t \x03(\x05R\x05dests\"E\n" +
	"\x04Move\x12\x10\n" +
	"\x03pod\x18\x01 \x01(\x05R\x03pod\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\x05R\x06toNode\x12\x12\n" +
	"\x04gpus\x18\x03 \x03(\x05R\x04gpus\"\x90\x02\n" +
	"\rDefragRequest\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.gpupack.v1.NodeR\x05nodes\x12)\n" +
	"\ablocked\x18\x02 \x03(\v2\x0f.gpupack.v1.PodR\ablocked\x12-\n" +
	"\amovable\x18\x03 \x03(\v2\x13.gpupack.v1.MovableR\amovable\x12\x1b\n" +
	"\tmax_moves\x18\x04 \x01(\x05R\bmaxMoves\x12 \n" +
	"\ftime_limit_s\x18\x05 \x01(\x01R\n" +
	"timeLimitS\x12$\n" +
	"\rdeterministic\x18\x06 \x01(\bR\rdeterministic\x12\x18\n" +
	"\aworkers\x18\a \x01(\x05R\aworkers\"\xcd\x01\n" +
	"\x0eDefragResponse\x12&\n" +
	"\x05moves\x18\x01 \x03(\v2\x10.gpupack.v1.MoveR\x05moves\x126\n" +
	"\n" +
	"placements\x18\x02 \x03(\v2\x16.gpupack.v1.AssignmentR\n" +
	"placements\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x15\n" +
	"\x06wall_s\x18\x04 \x01(\x01R\x05wallS\x12\x18\n" +
	"\abenefit\x18\x05 \x01(\x03R\abenefit\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x03R\x04cost\"\x0f\n" +
	"\rHealthRequest\"*\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion2\xc8\x01\n" +
	"\x06Solver\x12<\n" +
	"\x05Place\x12\x18.gpupack.v1.PlaceRequest\x1a\x19.gpupack.v1.PlaceResponse\x12?\n" +
	"\x06Defrag\x12\x19.gpupack.v1.DefragRequest\x1a\x1a.gpupack.v1.DefragResponse\x12?\n" +
	"\x06Health\x12\x19.gpupack.v1.HealthRequest\x1a\x1a.gpupack.v1.HealthResponseB$Z\"gpupack/proto/gpupack/v1;gpupackv1b\x06proto3"

var (
	file_gpupack_v1_solver_proto_rawDescOnce sync.Once
	file_gpupack_v1_solver_proto_rawDescData []byte
)

func file_gpupack_v1_solver_proto_rawDescGZIP() []byte {
	file_gpupack_v1_solver_proto_rawDescOnce.Do(func() {
		file_gpupack_v1_solver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gpupack_v1_solver_proto_rawDesc), len(file_gpupack_v1_solver_proto_rawDesc)))
	})
	return file_gpupack_v1_solver_proto_rawDescData
}

var file_gpupack_v1_solver_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_gpupack_v1_solver_proto_goTypes = []any{
	(*TypicalClass)(nil),   // 0: gpupack.v1.TypicalClass
	(*Node)(nil),           // 1: gpupack.v1.Node
	(*Pod)(nil),            // 2: gpupack.v1.Pod
	(*Assignment)(nil),     // 3: gpupack.v1.Assignment
	(*Pattern)(nil),        // 4: gpupack.v1.Pattern
	(*PlaceRequest)(nil),   // 5: gpupack.v1.PlaceRequest
	(*PlaceResponse)(nil),  // 6: gpupack.v1.PlaceResponse
	(*Movable)(nil),        // 7: gpupack.v1.Movable
	(*Move)(nil),           // 8: gpupack.v1.Move
	(*DefragRequest)(nil),  // 9: gpupack.v1.DefragRequest
	(*DefragResponse)(nil), // 10: gpupack.v1.DefragResponse
	(*HealthRequest)(nil),  // 11: gpupack.v1.HealthRequest
	(*HealthResponse)(nil), // 12: gpupack.v1.HealthResponse
}
var file_gpupack_v1_solver_proto_depIdxs = []int32{
	3,  // 0: gpupack.v1.Pattern.assignments:type_name -> gpupack.v1.Assignment
	1,  // 1: gpupack.v1.PlaceRequest.nodes:type_name -> gpupack.v1.Node
	2,  // 2: gpupack.v1.PlaceRequest.pods:type_name -> gpupack.v1.Pod
	0,  // 3: gpupack.v1.PlaceRequest.classes:type_name -> gpupack.v1.TypicalClass
	3,  // 4: gpupack.v1.PlaceRequest.hint:type_name -> gpupack.v1.Assignment
	4,  // 5: gpupack.v1.PlaceRequest.patterns:type_name -> gpupack.v1.Pattern
	3,  // 6: gpupack.v1.PlaceResponse.assignments:type_name -> gpupack.v1.Assignment
	1,  // 7: gpupack.v1.DefragRequest.nodes:type_name -> gpupack.v1.Node
	2,  // 8: gpupack.v1.DefragRequest.blocked:type_name -> gpupack.v1.Pod
	7,  // 9: gpupack.v1.DefragRequest.movable:type_name -> gpupack.v1.Movable
	8,  // 10: gpupack.v1.DefragResponse.moves:type_name -> gpupack.v1.Move
	3,  // 11: gpupack.v1.DefragResponse.placements:type_name -> gpupack.v1.Assignment
	5,  // 12: gpupack.v1.Solver.Place:input_type -> gpupack.v1.PlaceRequest
	9,  // 13: gpupack.v1.Solver.Defrag:input_type -> gpupack.v1.DefragRequest
	11, // 14: gpupack.v1.Solver.Health:input_type -> gpupack.v1.HealthRequest
	6,  // 15: gpupack.v1.Solver.Place:output_type -> gpupack.v1.PlaceResponse
	10, // 16: gpupack.v1.Solver.Defrag:output_type -> gpupack.v1.DefragResponse
	12, // 17: gpupack.v1.Solver.Health:output_type -> gpupack.v1.HealthResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_gpupack_v1_solver_proto_init() }
func file_gpupack_v1_solver_proto_init() {
	if File_gpupack_v1_solver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gpupack_v1_solver_proto_rawDesc), len(file_gpupack_v1_solver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gpupack_v1_solver_proto_goTypes,
		DependencyIndexes: file_gpupack_v1_solver_proto_depIdxs,
		MessageInfos:      file_gpupack_v1_solver_proto_msgTypes,
	}.Build()
	File_gpupack_v1_solver_proto = out.File
	file_gpupack_v1_solver_proto_goTypes = nil
	file_gpupack_v1_solver_proto_depIdxs = nil
}
