# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import solver_pb2 as gpudefrag_dot_v1_dot_solver__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gpudefrag/v1/solver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SolverStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Place = channel.unary_unary(
                '/gpudefrag.v1.Solver/Place',
                request_serializer=gpudefrag_dot_v1_dot_solver__pb2.PlaceRequest.SerializeToString,
                response_deserializer=gpudefrag_dot_v1_dot_solver__pb2.PlaceResponse.FromString,
                _registered_method=True)
        self.Defrag = channel.unary_unary(
                '/gpudefrag.v1.Solver/Defrag',
                request_serializer=gpudefrag_dot_v1_dot_solver__pb2.DefragRequest.SerializeToString,
                response_deserializer=gpudefrag_dot_v1_dot_solver__pb2.DefragResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/gpudefrag.v1.Solver/Health',
                request_serializer=gpudefrag_dot_v1_dot_solver__pb2.HealthRequest.SerializeToString,
                response_deserializer=gpudefrag_dot_v1_dot_solver__pb2.HealthResponse.FromString,
                _registered_method=True)


class SolverServicer:
    """Missing associated documentation comment in .proto file."""

    def Place(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Defrag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Place': grpc.unary_unary_rpc_method_handler(
                    servicer.Place,
                    request_deserializer=gpudefrag_dot_v1_dot_solver__pb2.PlaceRequest.FromString,
                    response_serializer=gpudefrag_dot_v1_dot_solver__pb2.PlaceResponse.SerializeToString,
            ),
            'Defrag': grpc.unary_unary_rpc_method_handler(
                    servicer.Defrag,
                    request_deserializer=gpudefrag_dot_v1_dot_solver__pb2.DefragRequest.FromString,
                    response_serializer=gpudefrag_dot_v1_dot_solver__pb2.DefragResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=gpudefrag_dot_v1_dot_solver__pb2.HealthRequest.FromString,
                    response_serializer=gpudefrag_dot_v1_dot_solver__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gpudefrag.v1.Solver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gpudefrag.v1.Solver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Solver:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Place(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpudefrag.v1.Solver/Place',
            gpudefrag_dot_v1_dot_solver__pb2.PlaceRequest.SerializeToString,
            gpudefrag_dot_v1_dot_solver__pb2.PlaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Defrag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpudefrag.v1.Solver/Defrag',
            gpudefrag_dot_v1_dot_solver__pb2.DefragRequest.SerializeToString,
            gpudefrag_dot_v1_dot_solver__pb2.DefragResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gpudefrag.v1.Solver/Health',
            gpudefrag_dot_v1_dot_solver__pb2.HealthRequest.SerializeToString,
            gpudefrag_dot_v1_dot_solver__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
